#!/usr/bin/env bash
set -Eeuo pipefail
readonly ROOT="$(cd "$(dirname "$0")/.." && pwd)"
test -f "$ROOT/deploy/systemd/hearth-staging-native-test-slot.service.in"
test -f "$ROOT/hearth-start/src/main/resources/application-staging-test.yml"
test -x "$ROOT/deploy/provision-staging-test-slot.sh"
test -x "$ROOT/deploy/teardown-staging-test-slot.sh"
grep -Fq 'Conflicts=hearth-staging-native-app.service' "$ROOT/deploy/systemd/hearth-staging-native-test-slot.service.in"
grep -Fq 'HEARTH_TEST_SLOT_MINIMUM_AVAILABLE_KIB=655360' "$ROOT/deploy/lib/staging-test-slot.sh"
grep -Fq 'MemAvailable' "$ROOT/deploy/run-staging-e2e-tests.sh"
grep -Fq 'readonly DATABASE="hearth_${SUITE}_${RUN_ID//t/_}"' "$ROOT/deploy/provision-staging-test-slot.sh"
grep -Fq 'readonly DB_USER="h_${USER_SUITE}_${RUN_ID//t/_}"' "$ROOT/deploy/provision-staging-test-slot.sh"
grep -Fq 'readonly NAMESPACE="hearth:staging:test:${SUITE}:${RUN_ID}:"' "$ROOT/deploy/provision-staging-test-slot.sh"
grep -Fq 'SPRING_PROFILES_ACTIVE=staging-test' "$ROOT/deploy/provision-staging-test-slot.sh"
grep -Fq 'HEARTH_REDIS_DATABASE' "$ROOT/deploy/provision-staging-test-slot.sh"
grep -Fq 'HEARTH_NATIVE_STAGING_IT_REDIS_DB' "$ROOT/deploy/provision-staging-test-slot.sh"
grep -Fq 'HEARTH_NATIVE_STAGING_E2E_REDIS_DB' "$ROOT/deploy/provision-staging-test-slot.sh"
grep -Fq 'HEARTH_NATIVE_STAGING_IT_REDIS_DB=12' "$ROOT/deploy/hearth-native.conf.example"
grep -Fq 'HEARTH_NATIVE_STAGING_E2E_REDIS_DB=13' "$ROOT/deploy/hearth-native.conf.example"
grep -Fq 'on-profile: staging-test' "$ROOT/hearth-start/src/main/resources/application-staging-test.yml"
grep -Fq 'redis_cli --scan' "$ROOT/deploy/teardown-staging-test-slot.sh"
! grep -Eq 'FLUSHDB|FLUSHALL' "$ROOT/deploy/teardown-staging-test-slot.sh"
grep -Fq 'provision-staging-test-slot.sh' "$ROOT/deploy/lib/staging-test-slot.sh"
grep -Fq 'teardown-staging-test-slot.sh' "$ROOT/deploy/lib/staging-test-slot.sh"
grep -Fq 'journalctl --unit' "$ROOT/deploy/lib/staging-test-slot.sh"
grep -Fq 'Hearth staging service emitted WARNING' "$ROOT/deploy/lib/staging-test-slot.sh"
grep -Fq 'hearth_test_slot_begin integration' "$ROOT/deploy/run-staging-integration-tests.sh"
grep -Fq 'hearth_test_slot_begin e2e' "$ROOT/deploy/run-staging-e2e-tests.sh"
grep -Fq 'sudo -n -u ubuntu -- bash -c' "$ROOT/deploy/run-staging-e2e-tests.sh"
printf 'Hearth staging test-slot isolation contract passed.\n'
